version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: coba_docker
      MYSQL_USER: user1
      MYSQL_PASSWORD: 123
    ports:
      - "3030:3030"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

  pythonapp:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    depends_on:
      - mysql
