version: '3'
services:
  python-jupyter:
    build:
      context: ../
      dockerfile: syseng/docker/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./app/src:/app
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=my_database
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=user123

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: my_database
      MYSQL_USER: user1
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "8080:80"
